void Demons_Lex()
{
    fill_solid(leds, 64, CRGB::Black);
    FastLED.show();
    delay(20);
    leds[3] = CRGB::Green;
    leds[4] = CRGB::Purple;
    leds[8] = CRGB::Purple;
    leds[9] = CRGB::Purple;
    leds[10] = CRGB::Purple;
    leds[11] = CRGB::Purple;
    leds[12] = CRGB::Purple;
    leds[13] = CRGB::Purple;
    leds[18] = CRGB::Purple;
    leds[19] = CRGB::Red;
    leds[20] = CRGB::Red;
    leds[21] = CRGB::Purple;
    leds[22] = CRGB::Purple;
    leds[23] = CRGB::Purple;
    leds[24] = CRGB::Purple;
    leds[25] = CRGB::Purple;
    leds[26] = CRGB::Purple;
    leds[27] = CRGB::Purple;
    leds[28] = CRGB::Purple;
    leds[29] = CRGB::Purple;
    leds[35] = CRGB::Purple;
    leds[36] = CRGB::Purple;
    leds[37] = CRGB::Purple;
    leds[38] = CRGB::Purple;
    leds[39] = CRGB::Purple;
    leds[40] = CRGB::Purple;
    leds[41] = CRGB::Purple;
    leds[42] = CRGB::Purple;
    leds[43] = CRGB::Purple;
    leds[51] = CRGB::Purple;
    leds[52] = CRGB::Purple;
    leds[55] = CRGB::Purple;
    leds[56] = CRGB::Purple;
    leds[57] = CRGB::Purple;
    leds[58] = CRGB::Purple;
    FastLED.show();
    delay(40);

    leds[8] = CRGB::Purple;
    leds[9] = CRGB::Purple;
    leds[10] = CRGB::Purple;
    leds[13] = CRGB::Purple;
    leds[21] = CRGB::Red;
    leds[22] = CRGB::Red;
    leds[23] = CRGB::Black;
    leds[24] = CRGB::Blue;
    leds[25] = CRGB::Purple;
    leds[26] = CRGB::Blue;
    leds[28] = CRGB::Purple;
    leds[29] = CRGB::Purple;
    leds[37] = CRGB::Purple;
    leds[38] = CRGB::Purple;
    leds[40] = CRGB::Purple;
    leds[42] = CRGB::Black;
    leds[52] = CRGB::Black;
    FastLED.show();
    delay(40);

    leds[2] = CRGB::Green;
    leds[3] = CRGB::Purple;
    leds[4] = CRGB::Black;
    leds[8] = CRGB::Black;
    leds[9] = CRGB::Purple;
    leds[11] = CRGB::Purple;
    leds[12] = CRGB::Purple;
    leds[13] = CRGB::Purple;
    leds[14] = CRGB::Purple;
    leds[17] = CRGB::Purple;
    leds[18] = CRGB::Red;
    leds[21] = CRGB::Red;
    leds[22] = CRGB::Black;
    leds[24] = CRGB::Blue;
    leds[29] = CRGB::Purple;
    leds[30] = CRGB::Purple;
    leds[34] = CRGB::Purple;
    leds[35] = CRGB::Purple;
    leds[36] = CRGB::Purple;
    leds[37] = CRGB::Purple;
    leds[38] = CRGB::Purple;
    leds[40] = CRGB::Purple;
    leds[41] = CRGB::Purple;
    leds[42] = CRGB::Purple;
    leds[43] = CRGB::Black;
    leds[44] = CRGB::Purple;
    leds[50] = CRGB::Purple;
    leds[51] = CRGB::Black;
    leds[54] = CRGB::Purple;
    leds[56] = CRGB::Black;
    leds[57] = CRGB::Purple;
    leds[59] = CRGB::Purple;
    FastLED.show();
    delay(40);

    leds[1] = CRGB::Green;
    leds[21] = CRGB::Black;
    leds[24] = CRGB(0, 0, 157);
    leds[25] = CRGB::Purple;
    leds[29] = CRGB::Purple;
    leds[30] = CRGB::Purple;
    leds[35] = CRGB::Purple;
    leds[41] = CRGB::Purple;
    leds[56] = CRGB::Black;
    FastLED.show();
    delay(40);

    leds[1] = CRGB::Black;
    leds[2] = CRGB::Black;
    leds[3] = CRGB::Black;
    leds[8] = CRGB::Blue;
    leds[9] = CRGB::Black;
    leds[10] = CRGB::Black;
    leds[11] = CRGB::Black;
    leds[12] = CRGB::Purple;
    leds[13] = CRGB::Purple;
    leds[14] = CRGB::Green;
    leds[16] = CRGB::Purple;
    leds[17] = CRGB::Purple;
    leds[18] = CRGB::Purple;
    leds[19] = CRGB::Purple;
    leds[20] = CRGB::Purple;
    leds[21] = CRGB::Purple;
    leds[23] = CRGB::Blue;
    leds[24] = CRGB::Purple;
    leds[25] = CRGB::Black;
    leds[26] = CRGB::Black;
    leds[27] = CRGB::Red;
    leds[28] = CRGB::Red;
    leds[29] = CRGB::Red;
    leds[31] = CRGB::Purple;
    leds[32] = CRGB::Purple;
    leds[33] = CRGB::Purple;
    leds[34] = CRGB::Purple;
    leds[35] = CRGB::Purple;
    leds[36] = CRGB::Purple;
    leds[37] = CRGB::Purple;
    leds[40] = CRGB::Purple;
    leds[41] = CRGB::Purple;
    leds[43] = CRGB::Purple;
    leds[45] = CRGB::Purple;
    leds[46] = CRGB::Purple;
    leds[48] = CRGB::Purple;
    leds[49] = CRGB::Purple;
    leds[50] = CRGB::Black;
    leds[52] = CRGB::Purple;
    leds[53] = CRGB::Purple;
    leds[54] = CRGB::Purple;
    leds[57] = CRGB::Purple;
    leds[58] = CRGB::Purple;
    leds[60] = CRGB::Purple;
    leds[61] = CRGB::Purple;
    FastLED.show();
    delay(40);
    for (i = 0; i <= 4; i++)
    {
        leds[1] = CRGB::Black;
        leds[2] = CRGB::Black;
        leds[3] = CRGB::Black;
        leds[4] = CRGB::Black;
        leds[8] = CRGB::Black;
        leds[9] = CRGB::Blue;
        leds[10] = CRGB::Black;
        leds[11] = CRGB::Black;
        leds[12] = CRGB::Black;
        leds[13] = CRGB::Purple;
        leds[14] = CRGB::Green;
        leds[16] = CRGB::Purple;
        leds[17] = CRGB::Purple;
        leds[18] = CRGB::Purple;
        leds[19] = CRGB::Purple;
        leds[20] = CRGB::Purple;
        leds[21] = CRGB::Black;
        leds[24] = CRGB::Purple;
        leds[27] = CRGB::Black;
        leds[30] = CRGB::Red;
        leds[31] = CRGB::Purple;
        leds[32] = CRGB::Purple;
        leds[33] = CRGB::Purple;
        leds[34] = CRGB::Purple;
        leds[35] = CRGB::Blue;
        leds[37] = CRGB::Purple;
        leds[38] = CRGB::Blue;
        leds[39] = CRGB::Purple;
        leds[40] = CRGB::Black;
        leds[41] = CRGB::Purple;
        leds[43] = CRGB::Purple;
        leds[44] = CRGB::Purple;
        leds[49] = CRGB::Black;
        leds[52] = CRGB::Purple;
        leds[53] = CRGB::Black;
        leds[55] = CRGB::Black;
        leds[57] = CRGB::Black;
        leds[58] = CRGB::Purple;
        leds[59] = CRGB::Black;
        leds[60] = CRGB::Purple;
        leds[61] = CRGB::Purple;
        FastLED.setBrightness(60 - 15 * i);
        FastLED.show();
        delay(250 - 60 * i);

        leds[1] = CRGB::Green;
        leds[2] = CRGB::Purple;
        leds[3] = CRGB::Black;
        leds[4] = CRGB::Black;
        leds[8] = CRGB::Black;
        leds[9] = CRGB::Black;
        leds[11] = CRGB::Purple;
        leds[12] = CRGB::Purple;
        leds[13] = CRGB::Purple;
        leds[14] = CRGB::Purple;
        leds[15] = CRGB::Purple;
        leds[16] = CRGB::Purple;
        leds[17] = CRGB::Red;
        leds[18] = CRGB::Red;
        leds[19] = CRGB::Red;
        leds[20] = CRGB::Black;
        leds[23] = CRGB::Blue;
        leds[24] = CRGB::Blue;
        leds[26] = CRGB::Blue;
        leds[27] = CRGB::Purple;
        leds[28] = CRGB::Blue;
        leds[29] = CRGB::Purple;
        leds[30] = CRGB::Purple;
        leds[31] = CRGB::Purple;
        leds[32] = CRGB::Black;
        leds[33] = CRGB::Purple;
        leds[34] = CRGB::Purple;
        leds[35] = CRGB::Purple;
        leds[36] = CRGB::Purple;
        leds[37] = CRGB::Purple;
        leds[38] = CRGB::Purple;
        leds[39] = CRGB::Purple;
        leds[40] = CRGB::Purple;
        leds[41] = CRGB::Purple;
        leds[42] = CRGB::Purple;
        leds[43] = CRGB::Purple;
        leds[44] = CRGB::Black;
        leds[45] = CRGB::Purple;
        leds[46] = CRGB::Black;
        leds[48] = CRGB::Black;
        leds[49] = CRGB::Purple;
        leds[52] = CRGB::Black;
        leds[53] = CRGB::Purple;
        leds[54] = CRGB::Purple;
        leds[58] = CRGB::Purple;
        leds[59] = CRGB::Purple;
        leds[60] = CRGB::Purple;
        leds[61] = CRGB::Black;
        FastLED.setBrightness(60 - 15 * i);
        FastLED.show();
        delay(250 - 60 * i);
    }
    delay(700);
    fill_solid(leds, 64, CRGB::Black);
    leds[1] = CRGB::Black;
    leds[2] = CRGB::Black;
    leds[3] = CRGB::Black;
    leds[4] = CRGB::Black;
    leds[8] = CRGB::Black;
    leds[9] = CRGB::Blue;
    leds[10] = CRGB::Black;
    leds[11] = CRGB::Black;
    leds[12] = CRGB::Black;
    leds[13] = CRGB::Purple;
    leds[14] = CRGB::Green;
    leds[16] = CRGB::Purple;
    leds[17] = CRGB::Purple;
    leds[18] = CRGB::Purple;
    leds[19] = CRGB::Purple;
    leds[20] = CRGB::Purple;
    leds[21] = CRGB::Black;
    leds[23] = CRGB::Blue;
    leds[24] = CRGB::Purple;
    leds[25] = CRGB::Black;
    leds[26] = CRGB::Black;
    leds[27] = CRGB::Black;
    leds[28] = CRGB::Red;
    leds[29] = CRGB::Red;
    leds[30] = CRGB::Red;
    leds[31] = CRGB::Purple;
    leds[32] = CRGB::Purple;
    leds[33] = CRGB::Purple;
    leds[34] = CRGB::Purple;
    leds[35] = CRGB::Blue;
    leds[36] = CRGB::Purple;
    leds[37] = CRGB::Purple;
    leds[38] = CRGB::Blue;
    leds[39] = CRGB::Purple;
    leds[40] = CRGB::Black;
    leds[41] = CRGB::Purple;
    leds[43] = CRGB::Purple;
    leds[44] = CRGB::Purple;
    leds[45] = CRGB::Purple;
    leds[46] = CRGB::Purple;
    leds[48] = CRGB::Purple;
    leds[49] = CRGB::Black;
    leds[52] = CRGB::Purple;
    leds[53] = CRGB::Black;
    leds[54] = CRGB::Purple;
    leds[55] = CRGB::Black;
    leds[57] = CRGB::Black;
    leds[58] = CRGB::Purple;
    leds[59] = CRGB::Black;
    leds[60] = CRGB::Purple;
    leds[61] = CRGB::Purple;
    FastLED.setBrightness(max_bright);
    playmusic(1, 0x05);
    FastLED.show();
    delay(3000);
}