void Demons_Finish()
{
  leds[6] = CRGB::Red;
  leds[15] = CRGB::Red;
  leds[16] = CRGB(74, 12, 111);
  leds[17] = CRGB::Black;
  leds[18] = CRGB::Black;
  leds[19] = CRGB::Black;
  leds[20] = CRGB::Black;
  leds[21] = CRGB::Black;
  leds[22] = CRGB::Black;
  leds[23] = CRGB(74, 12, 111);
  leds[24] = CRGB::Black;
  leds[25] = CRGB(74, 12, 111);
  leds[26] = CRGB::Black;
  leds[27] = CRGB::Black;
  leds[28] = CRGB::Black;
  leds[29] = CRGB::Black;
  leds[30] = CRGB(74, 12, 111);
  leds[31] = CRGB::Black;
  leds[32] = CRGB::Black;
  leds[33] = CRGB(74, 12, 111);
  leds[34] = CRGB(74, 12, 111);
  leds[35] = CRGB::Black;
  leds[36] = CRGB::Black;
  leds[37] = CRGB(74, 12, 111);
  leds[38] = CRGB(74, 12, 111);
  leds[39] = CRGB::Black;
  leds[40] = CRGB::Black;
  leds[41] = CRGB::Black;
  leds[42] = CRGB::Black;
  leds[43] = CRGB::Black;
  leds[44] = CRGB::Black;
  leds[45] = CRGB::Black;
  leds[46] = CRGB::Black;
  leds[47] = CRGB::Black;
  leds[48] = CRGB::Black;
  leds[49] = CRGB::Black;
  leds[50] = CRGB::Black;
  leds[51] = CRGB::Black;
  leds[52] = CRGB::Black;
  leds[53] = CRGB::Black;
  leds[54] = CRGB::Black;
  leds[55] = CRGB::Black;
  leds[56] = CRGB::Black;
  leds[57] = CRGB::Black;
  leds[58] = CRGB::Black;
  leds[59] = CRGB::Black;
  leds[60] = CRGB::Black;
  leds[61] = CRGB::Black;
  leds[62] = CRGB::Black;
  leds[63] = CRGB::Black;
  FastLED.show();
  delay(70);

  leds[6] = CRGB::Red;
  leds[8] = CRGB::Black;
  leds[55] = CRGB::Red;
  leds[56] = CRGB::Red;
  leds[57] = CRGB::Red;
  FastLED.show();
  delay(70);

  leds[15] = CRGB::Black;
  leds[48] = CRGB::Red;
  leds[63] = CRGB::Red;
  FastLED.show();
  delay(120);

  leds[0] = CRGB::Red;
  leds[1] = CRGB::Red;
  leds[2] = CRGB::Red;
  leds[6] = CRGB::Black;
  leds[8] = CRGB::Red;
  leds[15] = CRGB::Red;
  leds[16] = CRGB::Black;
  leds[23] = CRGB::Black;
  leds[25] = CRGB::Black;
  leds[30] = CRGB::Black;
  leds[33] = CRGB::Black;
  leds[34] = CRGB::Black;
  leds[37] = CRGB::Black;
  leds[38] = CRGB::Black;
  leds[55] = CRGB::Black;
  leds[56] = CRGB::Black;
  leds[57] = CRGB::Black;
  leds[61] = CRGB::Red;
  leds[62] = CRGB::Red;
  FastLED.show();
  delay(35);

  leds[6] = CRGB::Red;
  leds[7] = CRGB::Red;
  leds[16] = CRGB::Red;
  leds[48] = CRGB::Black;
  leds[62] = CRGB::Black;
  leds[63] = CRGB::Black;
  FastLED.show();
  delay(35);

  leds[0] = CRGB::Black;
  leds[1] = CRGB::Black;
  leds[2] = CRGB::Black;
  leds[5] = CRGB::Red;
  leds[31] = CRGB::Red;
  leds[32] = CRGB::Red;
  leds[47] = CRGB::Red;
  leds[55] = CRGB::Red;
  leds[56] = CRGB::Red;
  leds[57] = CRGB::Red;
  leds[58] = CRGB::Red;
  leds[61] = CRGB::Black;
  FastLED.show();
  delay(35);

  leds[3] = CRGB::Red;
  leds[4] = CRGB::Red;
  leds[7] = CRGB::Black;
  leds[8] = CRGB::Black;
  leds[15] = CRGB::Black;
  leds[16] = CRGB::Black;
  leds[40] = CRGB::Red;
  leds[48] = CRGB::Red;
  leds[49] = CRGB::Red;
  leds[63] = CRGB::Red;
  FastLED.show();
  delay(110);

  leds[0] = CRGB::Red;
  leds[1] = CRGB::Red;
  leds[2] = CRGB::Red;
  leds[5] = CRGB::Black;
  leds[6] = CRGB::Black;
  leds[14] = CRGB::Red;
  leds[23] = CRGB::Red;
  leds[24] = CRGB::Red;
  leds[31] = CRGB::Black;
  leds[32] = CRGB::Black;
  leds[39] = CRGB::Red;
  leds[56] = CRGB::Black;
  leds[57] = CRGB::Black;
  leds[58] = CRGB::Black;
  leds[61] = CRGB::Red;
  leds[62] = CRGB::Red;
  FastLED.show();
  delay(35);

  leds[3] = CRGB::Black;
  leds[4] = CRGB::Black;
  leds[7] = CRGB::Red;
  leds[8] = CRGB::Red;
  leds[9] = CRGB::Red;
  leds[15] = CRGB::Red;
  leds[16] = CRGB::Red;
  leds[40] = CRGB::Black;
  leds[47] = CRGB::Black;
  leds[48] = CRGB::Black;
  leds[49] = CRGB::Black;
  leds[55] = CRGB::Black;
  leds[58] = CRGB::Red;
  leds[59] = CRGB::Red;
  leds[60] = CRGB::Red;
  leds[63] = CRGB::Black;
  FastLED.show();
  delay(35);

  leds[1] = CRGB::Black;
  leds[2] = CRGB::Black;
  leds[4] = CRGB::Red;
  leds[5] = CRGB::Red;
  leds[6] = CRGB::Red;
  leds[24] = CRGB::Black;
  leds[31] = CRGB::Red;
  leds[32] = CRGB::Red;
  leds[39] = CRGB::Black;
  leds[54] = CRGB::Red;
  leds[55] = CRGB::Red;
  leds[56] = CRGB::Red;
  leds[57] = CRGB::Red;
  leds[61] = CRGB::Black;
  leds[62] = CRGB::Black;
  FastLED.show();
  delay(70);

  leds[0] = CRGB::Black;
  leds[1] = CRGB::Red;
  leds[2] = CRGB::Red;
  leds[3] = CRGB::Red;
  leds[4] = CRGB::Black;
  leds[5] = CRGB::Black;
  leds[6] = CRGB::Black;
  leds[7] = CRGB::Black;
  leds[8] = CRGB::Black;
  leds[9] = CRGB::Black;
  leds[13] = CRGB::Red;
  leds[15] = CRGB::Black;
  leds[16] = CRGB::Black;
  leds[24] = CRGB::Red;
  leds[31] = CRGB::Black;
  leds[32] = CRGB::Black;
  leds[39] = CRGB::Red;
  leds[40] = CRGB::Red;
  leds[46] = CRGB::Red;
  leds[47] = CRGB::Red;
  leds[48] = CRGB::Red;
  leds[49] = CRGB::Red;
  leds[50] = CRGB::Red;
  leds[54] = CRGB::Black;
  leds[56] = CRGB::Black;
  leds[57] = CRGB::Black;
  leds[58] = CRGB::Black;
  leds[59] = CRGB::Black;
  leds[61] = CRGB::Red;
  leds[62] = CRGB::Red;
  FastLED.show();
  delay(70);

  leds[3] = CRGB::Black;
  leds[6] = CRGB::Red;
  leds[8] = CRGB::Red;
  leds[9] = CRGB::Red;
  leds[10] = CRGB::Red;
  leds[15] = CRGB::Red;
  leds[16] = CRGB::Red;
  leds[17] = CRGB::Red;
  leds[22] = CRGB::Red;
  leds[30] = CRGB::Red;
  leds[31] = CRGB::Red;
  leds[39] = CRGB::Black;
  leds[40] = CRGB::Black;
  leds[46] = CRGB::Black;
  leds[47] = CRGB::Black;
  leds[48] = CRGB::Black;
  leds[49] = CRGB::Black;
  leds[53] = CRGB::Red;
  leds[55] = CRGB::Black;
  leds[58] = CRGB::Red;
  leds[59] = CRGB::Red;
  leds[62] = CRGB::Black;
  FastLED.show();
  delay(70);

  leds[1] = CRGB::Black;
  leds[2] = CRGB::Black;
  leds[4] = CRGB::Red;
  leds[5] = CRGB::Red;
  leds[11] = CRGB::Red;
  leds[13] = CRGB::Black;
  leds[14] = CRGB::Black;
  leds[15] = CRGB::Black;
  leds[22] = CRGB::Red;
  leds[23] = CRGB::Black;
  leds[24] = CRGB::Black;
  leds[32] = CRGB::Red;
  leds[33] = CRGB::Red;
  leds[40] = CRGB::Red;
  leds[41] = CRGB::Red;
  leds[46] = CRGB::Red;
  leds[47] = CRGB::Red;
  leds[50] = CRGB::Black;
  leds[52] = CRGB::Red;
  leds[54] = CRGB::Red;
  leds[55] = CRGB::Red;
  leds[57] = CRGB::Red;
  leds[60] = CRGB::Black;
  leds[61] = CRGB::Black;
  FastLED.show();
  delay(35);

  leds[2] = CRGB::Red;
  leds[3] = CRGB::Red;
  leds[5] = CRGB::Black;
  leds[6] = CRGB::Black;
  leds[8] = CRGB::Black;
  leds[9] = CRGB::Black;
  leds[10] = CRGB::Black;
  leds[12] = CRGB::Red;
  leds[13] = CRGB::Red;
  leds[16] = CRGB::Black;
  leds[17] = CRGB::Black;
  leds[22] = CRGB::Black;
  leds[24] = CRGB::Red;
  leds[25] = CRGB::Red;
  leds[30] = CRGB::Black;
  leds[31] = CRGB::Black;
  leds[38] = CRGB::Red;
  leds[39] = CRGB::Red;
  leds[45] = CRGB::Red;
  leds[49] = CRGB::Red;
  leds[50] = CRGB::Red;
  leds[52] = CRGB::Black;
  leds[53] = CRGB::Black;
  leds[55] = CRGB::Black;
  leds[57] = CRGB::Black;
  leds[58] = CRGB::Black;
  leds[59] = CRGB::Black;
  leds[61] = CRGB::Red;
  FastLED.show();
  delay(110);

  /*-----------------------------*/

  leds[2] = CRGB::Black;
  leds[3] = CRGB::Black;
  leds[4] = CRGB::Black;
  leds[9] = CRGB::Red;
  leds[11] = CRGB::Black;
  leds[14] = CRGB::Red;
  leds[17] = CRGB::Red;
  leds[18] = CRGB::Red;
  leds[21] = CRGB::Red;
  leds[22] = CRGB::Red;
  leds[30] = CRGB::Red;
  leds[32] = CRGB::Black;
  leds[33] = CRGB::Black;
  leds[40] = CRGB::Black;
  leds[41] = CRGB::Black;
  leds[45] = CRGB::Red;
  leds[46] = CRGB::Black;
  leds[47] = CRGB::Black;
  leds[49] = CRGB::Black;
  leds[51] = CRGB::Red;
  leds[52] = CRGB::Red;
  leds[54] = CRGB::Black;
  leds[59] = CRGB::Red;
  leds[60] = CRGB::Red;
  leds[61] = CRGB::Black;
  FastLED.show();
  delay(35);

  leds[14] = CRGB::Red;
  leds[45] = CRGB::Red;
  FastLED.show();
  delay(35);

  leds[9] = CRGB::Black;
  leds[11] = CRGB::Red;
  leds[13] = CRGB::Black;
  leds[14] = CRGB::Black;
  leds[17] = CRGB::Black;
  leds[18] = CRGB::Black;
  leds[19] = CRGB::Red;
  leds[20] = CRGB::Red;
  leds[21] = CRGB::Black;
  leds[22] = CRGB::Black;
  leds[24] = CRGB::Black;
  leds[30] = CRGB::Black;
  leds[33] = CRGB::Red;
  leds[34] = CRGB::Red;
  leds[37] = CRGB::Red;
  leds[39] = CRGB::Black;
  leds[42] = CRGB::Red;
  leds[44] = CRGB::Red;
  leds[45] = CRGB::Red;
  leds[50] = CRGB::Black;
  leds[51] = CRGB::Black;
  leds[52] = CRGB::Black;
  leds[59] = CRGB::Black;
  leds[60] = CRGB::Black;
  FastLED.show();
  delay(35);

  leds[11] = CRGB::Black;
  leds[12] = CRGB::Black;
  leds[20] = CRGB::Black;
  leds[21] = CRGB::Red;
  leds[25] = CRGB::Black;
  leds[26] = CRGB::Red;
  leds[29] = CRGB::Red;
  leds[33] = CRGB::Black;
  leds[34] = CRGB::Black;
  leds[37] = CRGB::Black;
  leds[38] = CRGB::Black;
  leds[42] = CRGB::Black;
  leds[43] = CRGB::Red;
  leds[45] = CRGB::Black;
  FastLED.show();
  delay(70);
  FastLED.show();
  delay(35);

  leds[19] = CRGB::Black;
  leds[20] = CRGB::Red;
  leds[21] = CRGB::Black;
  leds[26] = CRGB::Black;
  leds[29] = CRGB::Black;
  leds[37] = CRGB::Red;
  leds[44] = CRGB::Black;
  FastLED.show();
  delay(35);

  leds[35] = CRGB::Red;
  FastLED.show();
  delay(35);

  leds[20] = CRGB::Black;
  leds[35] = CRGB::Black;
  leds[37] = CRGB::Black;
  leds[43] = CRGB::Black;
  FastLED.show();
  delay(140);

  leds[27] = CRGB::Red;
  leds[28] = CRGB::Red;
  leds[35] = CRGB::Red;
  leds[36] = CRGB::Red;
  FastLED.show();
  delay(35);

  leds[10] = CRGB::Red;
  leds[11] = CRGB::Red;
  leds[12] = CRGB::Red;
  leds[13] = CRGB::Red;
  leds[17] = CRGB::Red;
  leds[18] = CRGB::Red;
  leds[19] = CRGB::Red;
  leds[20] = CRGB::Red;
  leds[21] = CRGB::Red;
  leds[22] = CRGB::Red;
  leds[25] = CRGB::Red;
  leds[26] = CRGB::Red;
  leds[29] = CRGB::Red;
  leds[30] = CRGB::Red;
  leds[33] = CRGB::Red;
  leds[34] = CRGB::Red;
  leds[37] = CRGB::Red;
  leds[38] = CRGB::Red;
  leds[41] = CRGB::Red;
  leds[42] = CRGB::Red;
  leds[43] = CRGB::Red;
  leds[44] = CRGB::Red;
  leds[45] = CRGB::Red;
  leds[46] = CRGB::Red;
  leds[50] = CRGB::Red;
  leds[51] = CRGB::Red;
  leds[52] = CRGB::Red;
  leds[53] = CRGB::Red;
  FastLED.show();
  delay(70);

  leds[2] = CRGB::Blue;
  leds[3] = CRGB::Blue;
  leds[4] = CRGB::Blue;
  leds[5] = CRGB::Blue;
  leds[9] = CRGB::Blue;
  leds[14] = CRGB::Blue;
  leds[16] = CRGB::Blue;
  leds[19] = CRGB::Black;
  leds[20] = CRGB::Black;
  leds[23] = CRGB::Blue;
  leds[24] = CRGB::Blue;
  leds[26] = CRGB::Black;
  leds[27] = CRGB::Black;
  leds[28] = CRGB::Black;
  leds[29] = CRGB::Black;
  leds[31] = CRGB::Blue;
  leds[32] = CRGB::Blue;
  leds[34] = CRGB::Black;
  leds[35] = CRGB::Black;
  leds[36] = CRGB::Black;
  leds[37] = CRGB::Black;
  leds[39] = CRGB::Blue;
  leds[40] = CRGB::Blue;
  leds[43] = CRGB::Black;
  leds[44] = CRGB::Black;
  leds[47] = CRGB::Blue;
  leds[49] = CRGB::Blue;
  leds[54] = CRGB::Blue;
  leds[58] = CRGB::Blue;
  leds[59] = CRGB::Blue;
  leds[60] = CRGB::Blue;
  leds[61] = CRGB::Blue;
  FastLED.show();
  delay(120);

  leds[1] = CRGB::Blue;
  leds[3] = CRGB::Black;
  leds[4] = CRGB::Black;
  leds[6] = CRGB::Blue;
  leds[7] = CRGB::Blue;
  leds[8] = CRGB::Blue;
  leds[9] = CRGB::Black;
  leds[10] = CRGB::Black;
  leds[11] = CRGB::Black;
  leds[12] = CRGB::Black;
  leds[13] = CRGB::Black;
  leds[14] = CRGB::Black;
  leds[15] = CRGB::Blue;
  leds[17] = CRGB::Black;
  leds[18] = CRGB::Black;
  leds[19] = CRGB::Red;
  leds[20] = CRGB::Red;
  leds[22] = CRGB::Black;
  leds[24] = CRGB::Black;
  leds[25] = CRGB::Black;
  leds[26] = CRGB::Red;
  leds[27] = CRGB::Red;
  leds[28] = CRGB::Red;
  leds[29] = CRGB::Red;
  leds[30] = CRGB::Black;
  leds[31] = CRGB::Black;
  leds[32] = CRGB::Black;
  leds[33] = CRGB::Black;
  leds[34] = CRGB::Red;
  leds[35] = CRGB::Red;
  leds[36] = CRGB::Red;
  leds[37] = CRGB::Red;
  leds[38] = CRGB::Black;
  leds[39] = CRGB::Black;
  leds[41] = CRGB::Black;
  leds[42] = CRGB::Red;
  leds[43] = CRGB::Red;
  leds[44] = CRGB::Red;
  leds[45] = CRGB::Red;
  leds[46] = CRGB::Black;
  leds[48] = CRGB::Blue;
  leds[49] = CRGB::Black;
  leds[50] = CRGB::Black;
  leds[51] = CRGB::Black;
  leds[52] = CRGB::Black;
  leds[53] = CRGB::Black;
  leds[54] = CRGB::Black;
  leds[55] = CRGB::Blue;
  leds[56] = CRGB::Blue;
  leds[57] = CRGB::Blue;
  leds[58] = CRGB::Black;
  leds[59] = CRGB::Black;
  leds[60] = CRGB::Black;
  leds[61] = CRGB::Blue;
  leds[62] = CRGB::Blue;
  leds[63] = CRGB::Blue;
  FastLED.show();
  delay(35);

  leds[0] = CRGB::Blue;
  leds[1] = CRGB::Black;
  leds[2] = CRGB::Black;
  leds[5] = CRGB::Black;
  leds[6] = CRGB::Black;
  leds[7] = CRGB::Blue;
  leds[8] = CRGB::Black;
  leds[11] = CRGB::Red;
  leds[12] = CRGB::Red;
  leds[15] = CRGB::Black;
  leds[16] = CRGB::Black;
  leds[18] = CRGB::Red;
  leds[23] = CRGB::Black;
  leds[25] = CRGB::Red;
  leds[30] = CRGB::Red;
  leds[33] = CRGB::Red;
  leds[38] = CRGB::Red;
  leds[40] = CRGB::Black;
  leds[42] = CRGB::Red;
  leds[45] = CRGB::Red;
  leds[47] = CRGB::Black;
  leds[48] = CRGB::Black;
  leds[51] = CRGB::Red;
  leds[52] = CRGB::Red;
  leds[55] = CRGB::Black;
  leds[56] = CRGB::Blue;
  leds[57] = CRGB::Black;
  leds[61] = CRGB::Black;
  leds[62] = CRGB::Black;
  leds[63] = CRGB::Blue;
  FastLED.show();
  delay(120);

  leds[0] = CRGB::Black;
  leds[2] = CRGB::Blue;
  leds[3] = CRGB::Blue;
  leds[4] = CRGB::Blue;
  leds[5] = CRGB::Blue;
  leds[7] = CRGB::Black;
  leds[9] = CRGB::Blue;
  leds[10] = CRGB::Red;
  leds[13] = CRGB::Red;
  leds[14] = CRGB::Blue;
  leds[16] = CRGB::Blue;
  leds[17] = CRGB::Red;
  leds[22] = CRGB::Red;
  leds[23] = CRGB::Blue;
  leds[24] = CRGB::Blue;
  leds[31] = CRGB::Blue;
  leds[32] = CRGB::Blue;
  leds[39] = CRGB::Blue;
  leds[40] = CRGB::Blue;
  leds[41] = CRGB::Red;
  leds[46] = CRGB::Red;
  leds[47] = CRGB::Blue;
  leds[49] = CRGB::Blue;
  leds[50] = CRGB::Red;
  leds[53] = CRGB::Red;
  leds[54] = CRGB::Blue;
  leds[56] = CRGB::Black;
  leds[58] = CRGB::Blue;
  leds[59] = CRGB::Blue;
  leds[60] = CRGB::Blue;
  leds[61] = CRGB::Blue;
  leds[63] = CRGB::Black;
  FastLED.show();
  delay(70);

  leds[1] = CRGB::Blue;
  leds[6] = CRGB::Blue;
  leds[8] = CRGB::Blue;
  leds[15] = CRGB::Blue;
  leds[48] = CRGB::Blue;
  leds[55] = CRGB::Blue;
  leds[57] = CRGB::Blue;
  leds[62] = CRGB::Blue;
  FastLED.show();
  delay(70);

  leds[0] = CRGB::Blue;
  leds[7] = CRGB::Blue;
  leds[19] = CRGB::Black;
  leds[20] = CRGB::Black;
  leds[26] = CRGB::Black;
  leds[27] = CRGB::Black;
  leds[28] = CRGB::Black;
  leds[29] = CRGB::Black;
  leds[34] = CRGB::Black;
  leds[35] = CRGB::Black;
  leds[36] = CRGB::Black;
  leds[37] = CRGB::Black;
  leds[43] = CRGB::Black;
  leds[44] = CRGB::Black;
  leds[56] = CRGB::Blue;
  leds[63] = CRGB::Blue;
  FastLED.show();
  delay(70);

  leds[10] = CRGB::Red;
  leds[11] = CRGB::Black;
  leds[12] = CRGB::Black;
  leds[13] = CRGB::Black;
  leds[18] = CRGB::Black;
  leds[21] = CRGB::Black;
  leds[25] = CRGB::Black;
  leds[27] = CRGB::Red;
  leds[28] = CRGB::Red;
  leds[30] = CRGB::Black;
  leds[33] = CRGB::Black;
  leds[35] = CRGB::Red;
  leds[36] = CRGB::Red;
  leds[38] = CRGB::Black;
  leds[41] = CRGB::Black;
  leds[42] = CRGB::Black;
  leds[45] = CRGB::Black;
  leds[50] = CRGB::Black;
  leds[51] = CRGB::Black;
  leds[52] = CRGB::Black;
  leds[53] = CRGB::Black;
  FastLED.show();
  delay(35);

  leds[3] = CRGB::Black;
  leds[4] = CRGB::Black;
  leds[9] = CRGB::Black;
  leds[10] = CRGB::Black;
  leds[14] = CRGB::Black;
  leds[17] = CRGB::Black;
  leds[18] = CRGB::Black;
  leds[19] = CRGB::Red;
  leds[20] = CRGB::Red;
  leds[22] = CRGB::Black;
  leds[24] = CRGB::Black;
  leds[26] = CRGB::Red;
  leds[29] = CRGB::Red;
  leds[31] = CRGB::Black;
  leds[32] = CRGB::Black;
  leds[34] = CRGB::Red;
  leds[36] = CRGB::Red;
  leds[37] = CRGB::Red;
  leds[39] = CRGB::Black;
  leds[42] = CRGB::Red;
  leds[43] = CRGB::Red;
  leds[44] = CRGB::Red;
  leds[45] = CRGB::Red;
  leds[46] = CRGB::Black;
  leds[49] = CRGB::Black;
  leds[54] = CRGB::Black;
  leds[59] = CRGB::Black;
  leds[60] = CRGB::Black;
  FastLED.show();
  delay(70);

  leds[0] = CRGB::Black;
  leds[1] = CRGB::Black;
  leds[2] = CRGB::Black;
  leds[5] = CRGB::Black;
  leds[6] = CRGB::Black;
  leds[7] = CRGB::Black;
  leds[8] = CRGB::Black;
  leds[10] = CRGB::Red;
  leds[11] = CRGB::Red;
  leds[12] = CRGB::Red;
  leds[13] = CRGB::Red;
  leds[15] = CRGB::Black;
  leds[16] = CRGB::Black;
  leds[17] = CRGB::Red;
  leds[18] = CRGB::Red;
  leds[21] = CRGB::Red;
  leds[22] = CRGB::Red;
  leds[23] = CRGB::Black;
  leds[25] = CRGB::Red;
  leds[30] = CRGB::Red;
  leds[33] = CRGB::Red;
  leds[38] = CRGB::Red;
  leds[40] = CRGB::Black;
  leds[41] = CRGB::Red;
  leds[46] = CRGB::Red;
  leds[47] = CRGB::Black;
  leds[48] = CRGB::Black;
  leds[50] = CRGB::Red;
  leds[51] = CRGB::Red;
  leds[52] = CRGB::Red;
  leds[53] = CRGB::Red;
  leds[55] = CRGB::Black;
  leds[56] = CRGB::Black;
  leds[57] = CRGB::Black;
  leds[58] = CRGB::Black;
  leds[61] = CRGB::Black;
  leds[62] = CRGB::Black;
  leds[63] = CRGB::Black;
  FastLED.show();
  delay(70);

  leds[1] = CRGB::Red;
  leds[2] = CRGB::Red;
  leds[3] = CRGB::Red;
  leds[4] = CRGB::Red;
  leds[5] = CRGB::Red;
  leds[6] = CRGB::Red;
  leds[8] = CRGB::Red;
  leds[9] = CRGB::Red;
  leds[14] = CRGB::Red;
  leds[15] = CRGB::Red;
  leds[16] = CRGB::Red;
  leds[23] = CRGB::Red;
  leds[24] = CRGB::Red;
  leds[31] = CRGB::Red;
  leds[32] = CRGB::Red;
  leds[39] = CRGB::Red;
  leds[40] = CRGB::Red;
  leds[47] = CRGB::Red;
  leds[48] = CRGB::Red;
  leds[49] = CRGB::Red;
  leds[54] = CRGB::Red;
  leds[55] = CRGB::Red;
  leds[57] = CRGB::Red;
  leds[58] = CRGB::Red;
  leds[59] = CRGB::Red;
  leds[60] = CRGB::Red;
  leds[61] = CRGB::Red;
  leds[62] = CRGB::Red;
  FastLED.show();
  delay(70);

  leds[0] = CRGB::Red;
  leds[7] = CRGB::Red;
  leds[56] = CRGB::Red;
  leds[63] = CRGB::Red;
  FastLED.show();
  delay(210);
}